# -*- coding: utf-8 -*-
"""practical-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dCQakuBYPur_fNRUSzLnRVj54-UzEVU_
"""

!pip install gensim nltk scikit-learn matplotlib

import nltk
import matplotlib.pyplot as plt
from gensim.models import Word2Vec
from nltk.corpus import brown
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

nltk.download('brown')

sentences = brown.sents()

data = [[word.lower() for word in sentence] for sentence in sentences]

print("Total Sentences:", len(data))
print(data[0])

model = Word2Vec(
    sentences=data,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4
)

print("Vocabulary Size:", len(model.wv))

print("Most similar to 'king':")
print(model.wv.most_similar('king', topn=5))

print("\nMost similar to 'computer':")
print(model.wv.most_similar('computer', topn=5))

result = model.wv.most_similar(
    positive=['woman', 'king'],
    negative=['man'],
    topn=5
)

print(result)

result = model.wv.most_similar(
    positive=['paris', 'italy'],
    negative=['france'],
    topn=5
)

print(result)

words = [

    'football', 'cricket', 'tennis', 'basketball', 'soccer',
    'player', 'coach', 'stadium', 'match', 'tournament',

    'pizza', 'burger', 'rice', 'pasta', 'coffee',
    'tea', 'bread', 'chicken', 'fruit', 'vegetable',

    'computer', 'internet', 'software', 'hardware', 'keyboard',
    'screen', 'database', 'network', 'python', 'robot',

    'school', 'college', 'teacher', 'student', 'library',

    'river', 'mountain', 'tree', 'forest', 'ocean',

    'car', 'train', 'airplane', 'bus', 'bicycle',

    'music', 'movie', 'book', 'phone', 'camera'
]

word_vectors = []

valid_words = []

for word in words:
    if word in model.wv:
        word_vectors.append(model.wv[word])
        valid_words.append(word)

print("Valid words:", len(valid_words))

pca = PCA(n_components=2)
result = pca.fit_transform(word_vectors)

plt.figure(figsize=(12,8))

for i, word in enumerate(valid_words):
    plt.scatter(result[i,0], result[i,1])
    plt.text(result[i,0]+0.01, result[i,1]+0.01, word)

plt.title("Word2Vec Embeddings Visualization using PCA")
plt.show()

import plotly.express as px

pca_3d = PCA(n_components=3)
result_3d = pca_3d.fit_transform(word_vectors)

fig = px.scatter_3d(
    result_3d,
    x=0,
    y=1,
    z=2,
    title="Word2Vec Embeddings Visualization using PCA (3D)"
)

for i, word in enumerate(valid_words):
    fig.add_annotation(
        x=result_3d[i,0],
        y=result_3d[i,1],
        text=word,
        showarrow=False,
        xanchor="left",
        yanchor="middle"
    )

fig.show()

import numpy as np

tsne = TSNE(
    n_components=2,
    random_state=42,
    perplexity=5
)

# Convert list of word vectors to a single NumPy array
word_vectors_np = np.array(word_vectors)
result_tsne = tsne.fit_transform(word_vectors_np)

plt.figure(figsize=(14,10))

for i, word in enumerate(valid_words):
    plt.scatter(result_tsne[i,0], result_tsne[i,1])
    plt.text(result_tsne[i,0]+0.3, result_tsne[i,1]+0.3, word)

plt.title("Word2Vec Embeddings Visualization using t-SNE")
plt.show()

