# ==========================================
# 1. IMPORTS SECTION
# ==========================================

# Import 'os' to interact with the operating system and read environment variables.
import os

# Import 'boto3', the official AWS SDK for Python, to access AWS security credentials.
import boto3

# Import 'load_dotenv' to securely read configuration variables from a local '.env' file.
from dotenv import load_dotenv

# Import OpenSearch client and HTTP connection handler to talk to our database.
from opensearchpy import OpenSearch, RequestsHttpConnection

# Import 'AWS4Auth' to handle the complex cryptographic signing required to access AWS OpenSearch.
from requests_aws4auth import AWS4Auth

# Import a custom Language Model (LLM) object from a local file/module named 'llm/bedrock.py'.
# This object ('llm') is likely pre-configured to talk to Amazon Bedrock (AWS's generative AI service).
from llm.bedrock import llm

# ==========================================
# 2. CONFIGURATION & AWS AUTHENTICATION
# ==========================================

# Load variables from the '.env' file into the system environment.
load_dotenv()

# Fetch the OpenSearch web address and the AWS region from the environment variables.
host = os.getenv("OPENSEARCH_HOST")
region = os.getenv("AWS_REGION")

# Use boto3 to automatically find and load AWS credentials (access key, secret key, token).
credentials = boto3.Session().get_credentials()

# Create the AWS authentication object required to securely log into the OpenSearch domain.
awsauth = AWS4Auth(
    credentials.access_key,
    credentials.secret_key,
    region,
    "es",  # "es" stands for Elasticsearch/OpenSearch
    session_token=credentials.token,
)


# ==========================================
# 3. OPENSEARCH CLIENT SETUP
# ==========================================

# Create the OpenSearch client instance. 
# This acts as our persistent connection to the database so we can perform searches.
client = OpenSearch(
    hosts=[{"host": host, "port": 443}],    # Target our specific host on the secure HTTPS port (443)
    http_auth=awsauth,                      # Use the AWS4Auth object to securely log in
    use_ssl=True,                           # Encrypt the traffic (HTTPS)
    verify_certs=True,                      # Ensure the server's security certificates are valid
    connection_class=RequestsHttpConnection # Handle the HTTP traffic routing
)


# ==========================================
# 4. RAG SEARCH FUNCTION
# ==========================================

def rag_search(query: str):
    """
    Retrieval-Augmented Generation (RAG) search function.
    Takes a plain-text user query, finds matching documents, and uses an LLM to generate an answer.
    """

    # --- STEP A: RETRIEVAL ---
    
    # Query the OpenSearch database using the user's question.
    response = client.search(
        index="company-docs", # The specific index (table) to search inside.
        body={
            "size": 3, # Limit the results to the top 3 most relevant documents.
            "query": {
                "match": {
                    "text": query # Perform a full-text search on the 'text' field using the user's query.
                }
            }
        }
    )

    # Extract the actual list of matching documents from the complex OpenSearch JSON response.
    hits = response["hits"]["hits"]

    # If the database returns no results, stop the function early and tell the user.
    if not hits:
        return "No relevant documents found."

    # Loop through the search results, extract the actual text from the "_source" dictionary of each result, 
    # and join them all together into one big string, separated by newlines.
    context = "\n".join([hit["_source"]["text"] for hit in hits])

    # --- STEP B: AUGMENTATION & GENERATION ---

    # Construct the "Prompt" (the instruction sent to the AI).
    # We use an f-string to inject both the retrieved 'context' and the user's 'query'.
    # IMPORTANT: We explicitly tell the AI to "Answer the user question using ONLY the provided context" 
    # to prevent it from hallucinating or making up answers outside of company policies.
    prompt = f"""
    Answer the user question using ONLY the provided context.

    Context:
    {context}

    Question:
    {query}
    """

    # Send the fully built prompt to the Large Language Model (e.g., via Amazon Bedrock).
    # The '.invoke()' method tells the model to read the prompt and generate a response.
    answer = llm.invoke(prompt)

    # The 'answer' object contains extra metadata, so we extract and return just the '.content' 
    # (the actual text response generated by the AI).
    return answer.content