# ==========================================
# 1. IMPORTS SECTION
# ==========================================

# Import 'TypedDict' from the typing module.
# This helps us define the exact shape and data types of our shared memory (State).
from typing import TypedDict

# Import tools from 'langgraph'. LangGraph is a library used to build stateful,
# multi-agent applications using graphs (nodes and edges).
# 'END' represents the final stopping point of the workflow.
# 'StateGraph' is the main class used to build the flowchart.
from langgraph.graph import END, StateGraph

# Import our custom Large Language Model (Amazon Bedrock) configuration.
from llm.bedrock import llm

# Import the RAG function we built in the previous script to search unstructured text.
from rag.rag_agent import rag_search

# Import a custom SQL agent function that presumably converts natural language to SQL and queries the database.
from sql_agent.sql_agent import run_sql_query

# ==========================================
# 2. GRAPH STATE DEFINITION
# ==========================================


# Define the "State" of our graph. Think of this as a shared clipboard or memory object
# that gets passed from step to step in our flowchart. Every node can read and write to this dictionary.
class GraphState(TypedDict, total=False):
    query: str  # The user's original question.
    query_type: str  # The classification of the query ("sql" or "rag").
    result: str  # The final answer generated by the tools.
    error: str  # An error message, if something goes wrong.


# ==========================================
# 3. GRAPH NODES (THE WORKERS)
# ==========================================
# Nodes are standard Python functions that take the current `state`, do some work,
# and return an updated dictionary to modify the state.


def classifier_node(state):
    """Analyzes the user's query and decides if it needs SQL or RAG."""
    try:
        # Standardize the query to lowercase for easier keyword matching.
        query = state["query"].lower()

        # ---------------------------------
        # FAST RULE-BASED SQL DETECTION
        # ---------------------------------
        # Create a list of buzzwords that strongly indicate the user is asking about structured HR/Finance data.
        sql_keywords = [
            "salary",
            "employee",
            "employees",
            "department",
            "departments",
            "count",
            "database",
            "table",
            "highest paid",
            "highest salary",
            "most salary",
            "engineering employees",
            "finance employees",
            "list employees",
            "who earns",
            "who has highest",
            "employee count",
        ]

        # If any of these buzzwords are in the query, bypass the AI and instantly classify it as "sql".
        # This saves time, money, and LLM processing power.
        if any(keyword in query for keyword in sql_keywords):
            return {"query_type": "sql"}

        # ---------------------------------
        # LLM FALLBACK CLASSIFIER
        # ---------------------------------
        # If no obvious keywords are found, ask the LLM to read the query and make a decision.
        prompt = f"""
        Classify the user query into ONE category only.

        Categories:
        sql
        rag

        SQL:
        Queries about: employees, salary, departments, analytics, database information

        RAG:
        Queries about: policies, company knowledge, informational documents, benefits, remote work, leave policy

        Query:
        {query}

        Return ONLY:
        sql
        OR
        rag
        """

        # Call the LLM to get a prediction.
        response = llm.invoke(prompt)

        # Clean up the AI's response (remove whitespace, make lowercase).
        category = response.content.strip().lower()

        # Fallback safeguard: if the AI hallucinated and returned something weird, default to "rag".
        if category not in ["sql", "rag"]:
            category = "rag"

        return {"query_type": category}

    except Exception as e:
        # If anything crashes, save the error to the state.
        return {"error": str(e)}


def sql_node(state: GraphState):
    """Executes the SQL agent if the query is classified as 'sql'."""
    try:
        query = state["query"]
        # Run the imported SQL tool using the user's question.
        result = run_sql_query(query)
        # Save the answer to the state.
        return {"result": result}
    except Exception as e:
        return {"error": str(e)}


def rag_node(state: GraphState):
    """Executes the RAG agent if the query is classified as 'rag'."""
    try:
        query = state["query"]
        # Run the imported RAG tool using the user's question.
        result = rag_search(query)
        # Save the answer to the state.
        return {"result": result}
    except Exception as e:
        return {"error": str(e)}


def error_node(state: GraphState):
    """Handles any errors that occurred in previous nodes to prevent the app from crashing."""
    # Retrieve the error from the state, or use a default message.
    error_message = state.get("error", "Unknown error occurred.")

    # Format a user-friendly failure message.
    return {"result": f"Graceful Failure: {error_message}"}


# ==========================================
# 4. CONDITIONAL ROUTERS (THE TRAFFIC COPS)
# ==========================================


def route_query(state: GraphState):
    """Reads the state after the classifier runs and decides which node to go to next."""

    # If the classifier generated an error, route straight to the error_node.
    if state.get("error"):
        return "error_node"

    # Grab the category decided by the classifier.
    query_type = state.get("query_type", "rag")

    # Return the name of the exact node the graph should trigger next.
    if query_type == "sql":
        return "sql_node"

    return "rag_node"


# ==========================================
# 5. BUILD AND COMPILE THE GRAPH
# ==========================================

# Initialize the state machine diagram, passing in our shared memory structure.
builder = StateGraph(GraphState)

# Add all our worker functions as actual "nodes" (boxes) in the flowchart.
builder.add_node("classifier", classifier_node)
builder.add_node("sql_node", sql_node)
builder.add_node("rag_node", rag_node)
builder.add_node("error_node", error_node)

# Set the starting point. Every time this workflow runs, it MUST start at the classifier.
builder.set_entry_point("classifier")


# -----------------------------------------
# Define the Edges (The arrows connecting the boxes)
# -----------------------------------------

# Add a conditional edge coming out of the 'classifier' node.
# It uses the `route_query` function to dynamically decide where the arrow points next.
builder.add_conditional_edges(
    "classifier",
    route_query,
    # Map the router's string outputs to the actual node names.
    {"sql_node": "sql_node", "rag_node": "rag_node", "error_node": "error_node"},
)

# Add a conditional edge coming out of the 'sql_node'.
# If there is an error in the state, route to the error_node. Otherwise, end the workflow (END).
builder.add_conditional_edges(
    "sql_node",
    lambda state: ("error_node" if state.get("error") else END),
    {"error_node": "error_node", END: END},
)

# Add a conditional edge coming out of the 'rag_node'.
# If there is an error in the state, route to the error_node. Otherwise, end the workflow (END).
builder.add_conditional_edges(
    "rag_node",
    lambda state: ("error_node" if state.get("error") else END),
    {"error_node": "error_node", END: END},
)

# Add a standard, static edge coming out of the 'error_node'.
# After printing the error, always end the workflow.
builder.add_edge("error_node", END)

# Compile the graph. This locks in the architecture and creates an executable application.
graph = builder.compile()


# ==========================================
# 6. EXECUTION / VISUALIZATION
# ==========================================

# This block only runs if this script is executed directly (not if it is imported into another file).
if __name__ == "__main__":

    # LangGraph can automatically generate a 'Mermaid' diagram (a text-based code representation of a flowchart).
    mermaid = graph.get_graph().draw_mermaid()

    # Print the diagram to the console.
    # You can copy/paste this output into a site like 'mermaid.live' to see a visual flowchart of your app!
    print("\nMermaid Diagram:\n")
    print(mermaid)
