# -*- coding: utf-8 -*-
"""practical-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EvKzIOIgXnJv-z9QOe5yXw5niNTMd2yv

###install necessary libraries
"""

!pip install pandas numpy scikit-learn nltk matplotlib seaborn

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

import matplotlib.pyplot as plt
import seaborn as sns

import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

"""###read csv data from spam.csv file, encoding added as some messages were corrupted with regular default encoding"""

df = pd.read_csv("spam.csv", encoding='latin-1')

df.head()

"""###change v1, v2 column name to label and messages"""

df = df[['v1', 'v2']]

df.columns = ['label', 'message']

df.head()

"""###change ham and spam language to 0 and 1 where ham is 0 and spam is 1"""

df['label'] = df['label'].map({
    'ham': 0,
    'spam': 1
})

df.head()

"""### Text Preprocessing where we are doing lowercasing, remove HTML tags, remove puncutation, remove numbers, and stopwords removal as well."""

import re
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    text = text.lower()
    text = remove_html_tags(text)
    text = re.sub(r'[\W_]+', ' ', text)
    text = re.sub(r'\d+', '', text)
    words = text.split()
    filtered_words = [word for word in words if word not in stop_words]
    text = ' '.join(filtered_words)
    return text.strip()
df['message'] = df['message'].apply(preprocess_text)

display(df.head())

"""###check for data distributions for spam messages or not"""

label_counts = df['label'].value_counts()

print("Distribution of spam or not:")
print(label_counts)

df_cleaned = df.dropna(subset=['label'])
X_train, X_test, y_train, y_test = train_test_split(
    df_cleaned['message'],
    df_cleaned['label'],
    test_size=0.2,
    random_state=42,
    stratify=df_cleaned['label']
)

tfidf = TfidfVectorizer()

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

lr_model = LogisticRegression(max_iter=1000)

lr_model.fit(X_train_tfidf, y_train)

y_pred_lr = lr_model.predict(X_test_tfidf)

print("logistic regression results")
print("accuracy :", accuracy_score(y_test, y_pred_lr))
print("precision:", precision_score(y_test, y_pred_lr))
print("recall   :", recall_score(y_test, y_pred_lr))
print("f1 Score :", f1_score(y_test, y_pred_lr))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_lr))

nb_model = MultinomialNB()

nb_model.fit(X_train_tfidf, y_train)

y_pred_nb = nb_model.predict(X_test_tfidf)

print("Naive Bayes Results")
print("Accuracy :", accuracy_score(y_test, y_pred_nb))
print("Precision:", precision_score(y_test, y_pred_nb))
print("Recall   :", recall_score(y_test, y_pred_nb))
print("F1 Score :", f1_score(y_test, y_pred_nb))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_nb))

map = confusion_matrix(y_test, y_pred_lr)

plt.figure(figsize=(5,4))
sns.heatmap(map, annot=True, fmt='d', cmap='Blues')

plt.title("Logistic Regression Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

stop_words = stopwords.words('english')

tfidf_stop = TfidfVectorizer(
    stop_words=stop_words
)

X_train_stop = tfidf_stop.fit_transform(X_train)
X_test_stop = tfidf_stop.transform(X_test)

lr_stop = LogisticRegression(max_iter=1000)

lr_stop.fit(X_train_stop, y_train)

y_pred_stop = lr_stop.predict(X_test_stop)

print("With Stopword Removal")
print("Precision:", precision_score(y_test, y_pred_stop))
print("Recall   :", recall_score(y_test, y_pred_stop))
print("F1 Score :", f1_score(y_test, y_pred_stop))

tfidf_ngram = TfidfVectorizer(
    ngram_range=(1,2)
)

X_train_ngram = tfidf_ngram.fit_transform(X_train)
X_test_ngram = tfidf_ngram.transform(X_test)

lr_ngram = LogisticRegression(max_iter=1000)

lr_ngram.fit(X_train_ngram, y_train)

y_pred_ngram = lr_ngram.predict(X_test_ngram)

print("Using Unigrams + Bigrams")
print("Precision:", precision_score(y_test, y_pred_ngram))
print("Recall   :", recall_score(y_test, y_pred_ngram))
print("F1 Score :", f1_score(y_test, y_pred_ngram))

"""its only in precision that naive bayes performs well, in all other evaluation meterics we see that TF-IDF with logistic regression performs better

using unigrams and bigrams and stopword removal does not hamper our performance in any meaningful manner
"""